drug:
    represented_as: node
    preferred_id: ddinter
    input_label: drug

drug interaction:
    is_a: association
    represented_as: edge
    input_label: drug_drug_interaction
    properties:
        level: str
        class: str
